
import os
import django
from django.db import connection

# Setup Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

def create_missing_tables():
    sql_commands = [
        """
        CREATE TABLE IF NOT EXISTS "users_groups" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
            "user_id" bigint NOT NULL, 
            "group_id" integer NOT NULL
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "users_user_permissions" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
            "user_id" bigint NOT NULL, 
            "permission_id" integer NOT NULL
        );
        """,
        # Constraints and Indexes for users_groups
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_groups_user_id_group_id_fc7788e8_uniq') THEN
                ALTER TABLE "users_groups" ADD CONSTRAINT "users_groups_user_id_group_id_fc7788e8_uniq" UNIQUE ("user_id", "group_id");
            END IF;
        END $$;
        """,
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_groups_user_id_f500bee5_fk_users_id') THEN
                ALTER TABLE "users_groups" ADD CONSTRAINT "users_groups_user_id_f500bee5_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
            END IF;
        END $$;
        """,
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_groups_group_id_2f3517aa_fk_auth_group_id') THEN
                ALTER TABLE "users_groups" ADD CONSTRAINT "users_groups_group_id_2f3517aa_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
            END IF;
        END $$;
        """,
        """
        CREATE INDEX IF NOT EXISTS "users_groups_user_id_f500bee5" ON "users_groups" ("user_id");
        """,
        """
        CREATE INDEX IF NOT EXISTS "users_groups_group_id_2f3517aa" ON "users_groups" ("group_id");
        """,
        
        # Constraints and Indexes for users_user_permissions
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_user_permissions_user_id_permission_id_3b86cbdf_uniq') THEN
                ALTER TABLE "users_user_permissions" ADD CONSTRAINT "users_user_permissions_user_id_permission_id_3b86cbdf_uniq" UNIQUE ("user_id", "permission_id");
            END IF;
        END $$;
        """,
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_user_permissions_user_id_92473840_fk_users_id') THEN
                ALTER TABLE "users_user_permissions" ADD CONSTRAINT "users_user_permissions_user_id_92473840_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
            END IF;
        END $$;
        """,
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_user_permissio_permission_id_6d08dcd2_fk_auth_perm') THEN
                ALTER TABLE "users_user_permissions" ADD CONSTRAINT "users_user_permissio_permission_id_6d08dcd2_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
            END IF;
        END $$;
        """,
        """
        CREATE INDEX IF NOT EXISTS "users_user_permissions_user_id_92473840" ON "users_user_permissions" ("user_id");
        """,
        """
        CREATE INDEX IF NOT EXISTS "users_user_permissions_permission_id_6d08dcd2" ON "users_user_permissions" ("permission_id");
        """
    ]

    with connection.cursor() as cursor:
        for sql in sql_commands:
            try:
                print(f"Executing: {sql[:50]}...")
                cursor.execute(sql)
            except Exception as e:
                print(f"Error executing SQL: {e}")

    print("Finished creating missing tables.")

if __name__ == "__main__":
    create_missing_tables()
