# Generated by Django 6.0.2 on 2026-03-05 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_enrollment_course_name_enrollment_course'),
        ('trainers', '0010_remove_livesession_course_batch_livesession_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='trainers.batch'),
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='enrollments',
        ),
    ]
