# Generated by Django 6.0.2 on 2026-03-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_enrollment_batch_add_enrollment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='batch',
            field=models.CharField(default='Batch 1', max_length=50),
        ),
    ]
