# Generated by Django 6.0.2 on 2026-02-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='portal_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
