# Generated by Django 6.0.2 on 2026-02-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_full_name_user_portal_link_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
