# Generated by Django 6.0.2 on 2026-02-21 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_livesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livesession',
            options={'ordering': ['scheduled_date', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='trainer',
        ),
        migrations.AddField(
            model_name='livesession',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livesession',
            name='end_time',
            field=models.TimeField(default='11:00:00'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='scheduled_date',
            field=models.DateField(default='2026-02-21'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='start_time',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='meeting_link',
            field=models.URLField(default='http://placeholder.com'),
        ),
    ]
