# Generated by Django 6.0.2 on 2026-02-21 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_alter_livesession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='trainer',
        ),
        migrations.AddField(
            model_name='course',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='courses_teaching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='meeting_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='scheduled_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
