# Generated by Django 6.0.2 on 2026-02-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0006_remove_course_trainer_course_trainers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='notes_file',
            field=models.FileField(blank=True, null=True, upload_to='modules/notes/'),
        ),
    ]
