# Generated by Django 6.0.2 on 2026-02-21 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0007_module_notes_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

def migrate_trainers(apps, schema_editor):
    from django.db import connection
    # Check if the old table exists
    with connection.cursor() as cursor:
        cursor.execute("SELECT count(*) FROM information_schema.tables WHERE table_name = 'courses_trainers'")
        if cursor.fetchone()[0] > 0:
            cursor.execute("SELECT course_id, user_id FROM courses_trainers")
            rows = cursor.fetchall()
            for course_id, user_id in rows:
                cursor.execute(
                    "INSERT INTO trainer_assignments (course_id, trainer_id, is_active, assigned_at) VALUES (%s, %s, %s, NOW()) ON CONFLICT DO NOTHING",
                    [course_id, user_id, True]
                )

class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0007_module_notes_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.course')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainer_assignments',
                'unique_together': {('course', 'trainer')},
            },
        ),
        migrations.RunPython(migrate_trainers, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='course',
            name='trainers',
        ),
        migrations.AddField(
            model_name='course',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='courses_teaching', through='trainers.TrainerAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
