# Generated by Django 6.0.2 on 2026-03-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0008_trainerassignment_alter_course_trainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='notes_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
