# Generated by Django 6.0.2 on 2026-03-05 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0012_delete_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainerassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='livesession',
            name='batch',
            field=models.CharField(default='Batch 1', max_length=50),
        ),
        migrations.AddField(
            model_name='module',
            name='batch',
            field=models.CharField(default='Batch 1', max_length=50),
        ),
        migrations.AddField(
            model_name='trainerassignment',
            name='batch',
            field=models.CharField(default='Batch 1', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='trainerassignment',
            unique_together={('course', 'trainer', 'batch')},
        ),
    ]
