# Generated by Django 6.0.2 on 2026-03-07 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0013_alter_trainerassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('ENROLLMENT', 'Enrollment'), ('SESSION_SCHEDULED', 'Live Session Scheduled'), ('MATERIAL_UPLOADED', 'Material Uploaded'), ('TRAINER_ASSIGNED', 'Trainer Assigned'), ('SYSTEM_UPDATE', 'System Update')], max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='trainers.course')),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
