# Generated by Django 6.0.2 on 2026-03-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0015_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='notes_file',
        ),
        migrations.AddField(
            model_name='module',
            name='notes_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='notes_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='notes_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
